// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package astro.com.samples;

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sample.Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 resultCode = 1;</code>
   */
  int getResultCode();

  /**
   * <code>string resultMessage = 2;</code>
   */
  java.lang.String getResultMessage();
  /**
   * <code>string resultMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getResultMessageBytes();
}
