// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package astro.com.samples;

public final class SampleProto {
  private SampleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sample_AstroMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sample_AstroMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sample_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sample_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sample.proto\022\006sample\"]\n\014AstroMessage\022\r" +
      "\n\005topic\030\001 \001(\t\022\r\n\005index\030\002 \001(\005\022\020\n\010datetime" +
      "\030\003 \001(\003\022\014\n\004uuid\030\004 \001(\t\022\017\n\007message\030\005 \001(\t\"3\n" +
      "\006Result\022\022\n\nresultCode\030\001 \001(\005\022\025\n\rresultMes" +
      "sage\030\002 \001(\t2?\n\006Sample\0225\n\013sendMessage\022\024.sa" +
      "mple.AstroMessage\032\016.sample.Result\"\000B(\n\021a" +
      "stro.com.samplesB\013SampleProtoP\001\242\002\003RTGb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sample_AstroMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sample_AstroMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sample_AstroMessage_descriptor,
        new java.lang.String[] { "Topic", "Index", "Datetime", "Uuid", "Message", });
    internal_static_sample_Result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sample_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sample_Result_descriptor,
        new java.lang.String[] { "ResultCode", "ResultMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
