// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageStructure.proto

package astro.com.message;

public interface ACKOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ACK)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ACKCode = 1;</code>
   */
  int getACKCode();
}
