// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageStructure.proto

package astro.com.message;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AstroMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AstroMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Return_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Return_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026MessageStructure.proto\"]\n\014AstroMessage" +
      "\022\r\n\005topic\030\001 \001(\t\022\r\n\005index\030\002 \001(\005\022\020\n\010dateti" +
      "me\030\003 \001(\003\022\014\n\004uuid\030\004 \001(\t\022\017\n\007message\030\005 \001(\t\"" +
      "\034\n\006Return\022\022\n\nreturnCode\030\001 \001(\00524\n\tTranspo" +
      "rt\022\'\n\013sendMessage\022\r.AstroMessage\032\007.Retur" +
      "n\"\000B)\n\021astro.com.messageB\014MessageProtoP\001" +
      "\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AstroMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AstroMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AstroMessage_descriptor,
        new java.lang.String[] { "Topic", "Index", "Datetime", "Uuid", "Message", });
    internal_static_Return_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Return_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Return_descriptor,
        new java.lang.String[] { "ReturnCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
