// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageStructure.proto

package astro.com.message;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AstroMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AstroMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Return_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Return_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026MessageStructure.proto\"]\n\014AstroMessage" +
      "\022\r\n\005topic\030\001 \001(\t\022\r\n\005index\030\002 \001(\005\022\020\n\010dateti" +
      "me\030\003 \001(\003\022\014\n\004uuid\030\004 \001(\t\022\017\n\007message\030\005 \001(\t\"" +
      "\203\003\n\006Return\022\022\n\nreturnCode\030\001 \001(\005\"2\n\013succes" +
      "sCode\022\026\n\022SuccessCodeDefault\020\000\022\013\n\007Success" +
      "\020d\"\237\001\n\020messageErrorCode\022\033\n\027MessageErrorC" +
      "odeDefault\020\000\022\026\n\021AstroMessage_Null\020\310\001\022\016\n\t" +
      "Uuid_Null\020\311\001\022\017\n\nTopic_Null\020\312\001\022\021\n\014Message" +
      "_Null\020\313\001\022\016\n\tDate_Zero\020\314\001\022\022\n\rIndex_Invali" +
      "d\020\315\001\"S\n\020storingErrorCode\022\033\n\027StoringError" +
      "codeDefault\020\000\022\017\n\nQueue_Full\020\255\002\022\021\n\014Storag" +
      "e_Full\020\256\002\":\n\tErrorCode\022\024\n\020ErrorCodeDefau" +
      "lt\020\000\022\027\n\022Unrecognized_Error\020\330\00424\n\tTranspo" +
      "rt\022\'\n\013sendMessage\022\r.AstroMessage\032\007.Retur" +
      "n\"\000B)\n\021astro.com.messageB\014MessageProtoP\001" +
      "\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AstroMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AstroMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AstroMessage_descriptor,
        new java.lang.String[] { "Topic", "Index", "Datetime", "Uuid", "Message", });
    internal_static_Return_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Return_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Return_descriptor,
        new java.lang.String[] { "ReturnCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
