// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageStructure.proto

package astro.com.message;

/**
 * Protobuf type {@code Return}
 */
public  final class Return extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Return)
    ReturnOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Return.newBuilder() to construct.
  private Return(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Return() {
    returnCode_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Return(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            returnCode_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return astro.com.message.MessageProto.internal_static_Return_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return astro.com.message.MessageProto.internal_static_Return_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            astro.com.message.Return.class, astro.com.message.Return.Builder.class);
  }

  /**
   * Protobuf enum {@code Return.successCode}
   */
  public enum successCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SuccessCodeDefault = 0;</code>
     */
    SuccessCodeDefault(0),
    /**
     * <code>Success = 100;</code>
     */
    Success(100),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SuccessCodeDefault = 0;</code>
     */
    public static final int SuccessCodeDefault_VALUE = 0;
    /**
     * <code>Success = 100;</code>
     */
    public static final int Success_VALUE = 100;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static successCode valueOf(int value) {
      return forNumber(value);
    }

    public static successCode forNumber(int value) {
      switch (value) {
        case 0: return SuccessCodeDefault;
        case 100: return Success;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<successCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        successCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<successCode>() {
            public successCode findValueByNumber(int number) {
              return successCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return astro.com.message.Return.getDescriptor().getEnumTypes().get(0);
    }

    private static final successCode[] VALUES = values();

    public static successCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private successCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Return.successCode)
  }

  /**
   * Protobuf enum {@code Return.messageErrorCode}
   */
  public enum messageErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MessageErrorCodeDefault = 0;</code>
     */
    MessageErrorCodeDefault(0),
    /**
     * <code>AstroMessage_Null = 200;</code>
     */
    AstroMessage_Null(200),
    /**
     * <code>Uuid_Null = 201;</code>
     */
    Uuid_Null(201),
    /**
     * <code>Topic_Null = 202;</code>
     */
    Topic_Null(202),
    /**
     * <code>Message_Null = 203;</code>
     */
    Message_Null(203),
    /**
     * <code>Date_Zero = 204;</code>
     */
    Date_Zero(204),
    /**
     * <code>Index_Invalid = 205;</code>
     */
    Index_Invalid(205),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MessageErrorCodeDefault = 0;</code>
     */
    public static final int MessageErrorCodeDefault_VALUE = 0;
    /**
     * <code>AstroMessage_Null = 200;</code>
     */
    public static final int AstroMessage_Null_VALUE = 200;
    /**
     * <code>Uuid_Null = 201;</code>
     */
    public static final int Uuid_Null_VALUE = 201;
    /**
     * <code>Topic_Null = 202;</code>
     */
    public static final int Topic_Null_VALUE = 202;
    /**
     * <code>Message_Null = 203;</code>
     */
    public static final int Message_Null_VALUE = 203;
    /**
     * <code>Date_Zero = 204;</code>
     */
    public static final int Date_Zero_VALUE = 204;
    /**
     * <code>Index_Invalid = 205;</code>
     */
    public static final int Index_Invalid_VALUE = 205;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static messageErrorCode valueOf(int value) {
      return forNumber(value);
    }

    public static messageErrorCode forNumber(int value) {
      switch (value) {
        case 0: return MessageErrorCodeDefault;
        case 200: return AstroMessage_Null;
        case 201: return Uuid_Null;
        case 202: return Topic_Null;
        case 203: return Message_Null;
        case 204: return Date_Zero;
        case 205: return Index_Invalid;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<messageErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        messageErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<messageErrorCode>() {
            public messageErrorCode findValueByNumber(int number) {
              return messageErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return astro.com.message.Return.getDescriptor().getEnumTypes().get(1);
    }

    private static final messageErrorCode[] VALUES = values();

    public static messageErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private messageErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Return.messageErrorCode)
  }

  /**
   * Protobuf enum {@code Return.storingErrorCode}
   */
  public enum storingErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>StoringErrorcodeDefault = 0;</code>
     */
    StoringErrorcodeDefault(0),
    /**
     * <code>Queue_Full = 301;</code>
     */
    Queue_Full(301),
    /**
     * <code>Storage_Full = 302;</code>
     */
    Storage_Full(302),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>StoringErrorcodeDefault = 0;</code>
     */
    public static final int StoringErrorcodeDefault_VALUE = 0;
    /**
     * <code>Queue_Full = 301;</code>
     */
    public static final int Queue_Full_VALUE = 301;
    /**
     * <code>Storage_Full = 302;</code>
     */
    public static final int Storage_Full_VALUE = 302;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static storingErrorCode valueOf(int value) {
      return forNumber(value);
    }

    public static storingErrorCode forNumber(int value) {
      switch (value) {
        case 0: return StoringErrorcodeDefault;
        case 301: return Queue_Full;
        case 302: return Storage_Full;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<storingErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        storingErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<storingErrorCode>() {
            public storingErrorCode findValueByNumber(int number) {
              return storingErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return astro.com.message.Return.getDescriptor().getEnumTypes().get(2);
    }

    private static final storingErrorCode[] VALUES = values();

    public static storingErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private storingErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Return.storingErrorCode)
  }

  /**
   * Protobuf enum {@code Return.ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ErrorCodeDefault = 0;</code>
     */
    ErrorCodeDefault(0),
    /**
     * <code>Unrecognized_Error = 600;</code>
     */
    Unrecognized_Error(600),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ErrorCodeDefault = 0;</code>
     */
    public static final int ErrorCodeDefault_VALUE = 0;
    /**
     * <code>Unrecognized_Error = 600;</code>
     */
    public static final int Unrecognized_Error_VALUE = 600;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorCode valueOf(int value) {
      return forNumber(value);
    }

    public static ErrorCode forNumber(int value) {
      switch (value) {
        case 0: return ErrorCodeDefault;
        case 600: return Unrecognized_Error;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return astro.com.message.Return.getDescriptor().getEnumTypes().get(3);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Return.ErrorCode)
  }

  public static final int RETURNCODE_FIELD_NUMBER = 1;
  private int returnCode_;
  /**
   * <code>int32 returnCode = 1;</code>
   */
  public int getReturnCode() {
    return returnCode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (returnCode_ != 0) {
      output.writeInt32(1, returnCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (returnCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, returnCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof astro.com.message.Return)) {
      return super.equals(obj);
    }
    astro.com.message.Return other = (astro.com.message.Return) obj;

    boolean result = true;
    result = result && (getReturnCode()
        == other.getReturnCode());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RETURNCODE_FIELD_NUMBER;
    hash = (53 * hash) + getReturnCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static astro.com.message.Return parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static astro.com.message.Return parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static astro.com.message.Return parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static astro.com.message.Return parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static astro.com.message.Return parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static astro.com.message.Return parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static astro.com.message.Return parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static astro.com.message.Return parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static astro.com.message.Return parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static astro.com.message.Return parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static astro.com.message.Return parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static astro.com.message.Return parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(astro.com.message.Return prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Return}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Return)
      astro.com.message.ReturnOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return astro.com.message.MessageProto.internal_static_Return_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return astro.com.message.MessageProto.internal_static_Return_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              astro.com.message.Return.class, astro.com.message.Return.Builder.class);
    }

    // Construct using astro.com.message.Return.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      returnCode_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return astro.com.message.MessageProto.internal_static_Return_descriptor;
    }

    @java.lang.Override
    public astro.com.message.Return getDefaultInstanceForType() {
      return astro.com.message.Return.getDefaultInstance();
    }

    @java.lang.Override
    public astro.com.message.Return build() {
      astro.com.message.Return result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public astro.com.message.Return buildPartial() {
      astro.com.message.Return result = new astro.com.message.Return(this);
      result.returnCode_ = returnCode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof astro.com.message.Return) {
        return mergeFrom((astro.com.message.Return)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(astro.com.message.Return other) {
      if (other == astro.com.message.Return.getDefaultInstance()) return this;
      if (other.getReturnCode() != 0) {
        setReturnCode(other.getReturnCode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      astro.com.message.Return parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (astro.com.message.Return) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int returnCode_ ;
    /**
     * <code>int32 returnCode = 1;</code>
     */
    public int getReturnCode() {
      return returnCode_;
    }
    /**
     * <code>int32 returnCode = 1;</code>
     */
    public Builder setReturnCode(int value) {
      
      returnCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 returnCode = 1;</code>
     */
    public Builder clearReturnCode() {
      
      returnCode_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Return)
  }

  // @@protoc_insertion_point(class_scope:Return)
  private static final astro.com.message.Return DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new astro.com.message.Return();
  }

  public static astro.com.message.Return getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Return>
      PARSER = new com.google.protobuf.AbstractParser<Return>() {
    @java.lang.Override
    public Return parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Return(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Return> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Return> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public astro.com.message.Return getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

