// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageStructure.proto

package astro.com.message;

public interface ReturnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Return)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 returnCode = 1;</code>
   */
  int getReturnCode();
}
